import { fail, redirect } from '@sveltejs/kit';
import type { PageServerLoad, Actions } from './$types';
import type { Event } from '$lib/types';
import { generateShortCode } from '$lib/short-codes';

export const load: PageServerLoad = async ({ parent, locals }) => {
	const parentData = await parent();

	if (!parentData.isAdmin) {
		throw redirect(303, '/admin');
	}

	// Get events the admin is assigned to via event_admins junction table
	const { data: eventAdmins, error } = await locals.supabase
		.from('event_admins')
		.select('event_id, events(*)')
		.eq('admin_id', parentData.admin.id)
		.order('created_at', { ascending: false });

	if (error) {
		console.error('Error fetching events:', error);
		return { events: [] as Event[], eventCodeMap: {} as Record<string, string>, error: error.message };
	}

	// Extract the events from the join result
	const events = eventAdmins
		.map(ea => ea.events as Event)
		.filter(Boolean)
		.sort((a, b) => new Date(b.created_at ?? 0).getTime() - new Date(a.created_at ?? 0).getTime());

	// Load event-type short codes for linking
	const eventIds = events.map(e => e.id);
	const eventCodeMap: Record<string, string> = {};

	if (eventIds.length > 0) {
		const { data: codes } = await locals.supabase
			.from('short_codes')
			.select('code, target_id')
			.eq('target_type', 'event')
			.in('target_id', eventIds);

		if (codes) {
			for (const c of codes) {
				eventCodeMap[c.target_id] = c.code;
			}
		}
	}

	return {
		events,
		eventCodeMap
	};
};

export const actions: Actions = {
	create: async ({ request, locals }) => {
		const { user } = await locals.safeGetSession();
		if (!user) {
			return fail(403, { error: 'Not authorized' });
		}

		// Verify user is admin and get their admin id
		const { data: currentAdmin } = await locals.supabase
			.from('admins')
			.select('id')
			.eq('user_id', user.id)
			.single();

		if (!currentAdmin) {
			return fail(403, { error: 'Not authorized' });
		}

		const formData = await request.formData();
		const name = formData.get('name')?.toString().trim();
		const date = formData.get('date')?.toString() || null;
		const maxPointsStr = formData.get('max_points')?.toString();
		const maxPoints = maxPointsStr ? parseInt(maxPointsStr, 10) : 5;

		if (!name) {
			return fail(400, { error: 'Event name is required' });
		}

		if (isNaN(maxPoints) || maxPoints < 1) {
			return fail(400, { error: 'Max points must be a positive number' });
		}

		// Create the event (manage_token is auto-generated by DB)
		const { data: event, error: eventError } = await locals.supabase
			.from('events')
			.insert({
				name,
				date: date || null,
				max_points: maxPoints
			})
			.select()
			.single();

		if (eventError) {
			console.error('Error creating event:', eventError);
			return fail(500, { error: 'Failed to create event' });
		}

		// Auto-assign creator to the event
		const { error: assignError } = await locals.supabase
			.from('event_admins')
			.insert({
				event_id: event.id,
				admin_id: currentAdmin.id
			});

		if (assignError) {
			console.error('Error assigning admin to event:', assignError);
			// Event was created but assignment failed - try to clean up
			await locals.supabase.from('events').delete().eq('id', event.id);
			return fail(500, { error: 'Failed to assign you to the event' });
		}

		// Generate short codes for the event (event + manage types)
		const { error: codeError } = await locals.supabase
			.from('short_codes')
			.insert([
				{ code: generateShortCode(), target_type: 'event', target_id: event.id },
				{ code: generateShortCode(), target_type: 'manage', target_id: event.id }
			]);

		if (codeError) {
			console.error('Error creating short codes:', codeError);
			// Non-fatal: event exists but codes failed. Log and continue.
		}

		return { success: true, eventId: event.id };
	},

	delete: async ({ request, locals }) => {
		const { user } = await locals.safeGetSession();
		if (!user) {
			return fail(403, { error: 'Not authorized' });
		}

		// Verify user is admin and get their admin id
		const { data: currentAdmin } = await locals.supabase
			.from('admins')
			.select('id')
			.eq('user_id', user.id)
			.single();

		if (!currentAdmin) {
			return fail(403, { error: 'Not authorized' });
		}

		const formData = await request.formData();
		const eventId = formData.get('eventId')?.toString();

		if (!eventId) {
			return fail(400, { error: 'Event ID is required' });
		}

		// Verify admin is assigned to this event
		const { data: assignment } = await locals.supabase
			.from('event_admins')
			.select('event_id')
			.eq('event_id', eventId)
			.eq('admin_id', currentAdmin.id)
			.single();

		if (!assignment) {
			return fail(403, { error: 'You are not assigned to this event' });
		}

		// Delete the event (CASCADE will handle related records)
		const { error } = await locals.supabase
			.from('events')
			.delete()
			.eq('id', eventId);

		if (error) {
			console.error('Error deleting event:', error);
			return fail(500, { error: 'Failed to delete event' });
		}

		return { deleted: true };
	}
};
